# Generated by Django 5.1.1 on 2024-09-29 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_procedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='patient',
        ),
        migrations.AddField(
            model_name='doctor',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='doctors.procedure'),
        ),
        migrations.AddField(
            model_name='patient',
            name='procedures',
            field=models.ManyToManyField(blank=True, related_name='patients', to='doctors.procedure'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='doctors.doctor'),
        ),
    ]
