# Generated by Django 5.1.1 on 2024-10-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_remove_doctor_procedure_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
